version: '3'

services:
  # Frontend sevice
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
  
  # Backend django and mongodb
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MAX_CHARACTER_LENGTH=1000
    ports:
      - "8000:8000"

  # Reverse proxy for frontend and backend port forwarding
  nginx-proxy:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    depends_on:
      - frontend
    networks:
      backend:
        - aliases:
            - nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf